/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CS_H_RPCGEN
#define	_CS_H_RPCGEN

#include <rpc/rpc.h>

struct cidtoken {
	u_char cid1[8];
	u_char enctoken[24];
};
typedef struct cidtoken cidtoken;

struct strmsg {
	int len;
	u_char firstname[100];
};
typedef struct strmsg strmsg;

struct str2msg {
	u_char lastname[100];
	u_char fstname[100];
	int len;
};
typedef struct str2msg str2msg;

struct gpa_1_argument {
	cidtoken arg1;
	strmsg arg2;
};
typedef struct gpa_1_argument gpa_1_argument;

struct last_1_argument {
	cidtoken arg1;
	strmsg arg2;
};
typedef struct last_1_argument last_1_argument;

#define	SP_PROG	0x34247123
#define	AS_VERS	1
#define	GPA	1
extern  float * gpa_1();
#define	LAST	2
extern  str2msg * last_1();
extern int sp_prog_1_freeresult();

/* the xdr functions */
extern bool_t xdr_cidtoken();
extern bool_t xdr_strmsg();
extern bool_t xdr_str2msg();
extern bool_t xdr_gpa_1_argument();
extern bool_t xdr_last_1_argument();

#endif /* !_CS_H_RPCGEN */
